### ISSUE TITLE
Replace Dependabot-preview with native Dependabot integration

### ISSUE THREAD

**Issue by jobara** [fluid-project/fluidic-11ty#29]
## Is your feature request related to a problem?
Dependabot is now natively supported in GitHub and does not require the Dependabot-Preview app. 

## Describe the solution you'd like
We should remove the app integration and update the configuration file as needed. 

See: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#moving-forward-from-dependabot-com-and-dependabot-preview

Dependabot has been whitelisted for CLAassistant, so making this change should also remove the CLAassistant checks related to Dependabot.

**Comment by greatislander** [comment]
@jobara I believe this is already done; the PRs that weren't whitelisted were opened before I completed the configuration migration (see https://github.com/fluid-project/fluidic-11ty/pull/23 for a PR opened and merged after the configuration was migrated from Dependabot Preview to Dependabot).

**Comment by jobara** [comment]
@greatislander in that case I think we can just remove the app integration, as it is still currently enabled. Let me know if you'd like me to do this.

**Comment by greatislander** [comment]
@jobara Yes, please— I don't have privileges to do so.

**Comment by jobara** [comment]
All done.
