### ISSUE TITLE
Project includes live Matomo configuration

### ISSUE THREAD

**Issue by greatislander** [fluid-project/fluidic-11ty#3]
## Describe the bug

Currently `fluidic-11ty` includes Matomo configuration for site ID 7. The ID should be removed from `assets/js/analytics.js` and the Matamo script should be commented out in [`layouts/default.html`](https://github.com/sachin10101998/fluidic-11ty/blob/master/src/_includes/layouts/default.html#L10) so that it can be added if desired rather than present by default.

### To reproduce

1. Run npm run eleventy.
2. Navigate to http://localhost:8080.
3. Observe that a connection is being made to https://analytics.inclusivedesign.ca.

### Expected behavior

As this is a starter kit, it should not include "live" configuration data, but rather guides/sample code on how to configure functionality such as analytics.

**Comment by sachin10101998** [comment]
@greatislander Fixed the file and commented it out from layouts too. Added tutorial link in readme file for sample codes.
